import { readFile } from 'node:fs/promises';
import { test, before, after } from 'node:test';
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { ref, uploadBytes, getBytes, listAll, deleteObject, updateMetadata } from 'firebase/storage';
let env;
const owner='owner-123', filename='11111111-1111-4111-8111-111111111111.omnibak';
const path=`backups/${owner}/${filename}`;
const payload=new Uint8Array([79,77,78,73,66,65,75,33,10,20,30]);
const metadata={contentType:'application/octet-stream'};
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-omni-backup',storage:{host:'127.0.0.1',port:9199,rules:await readFile(new URL('./storage.rules',import.meta.url),'utf8')}});});
after(async()=>env?.cleanup());
const own=()=>env.authenticatedContext(owner,{email:'owner@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}}).storage();
test('verified owner creates immutable backup',async()=>{await assertSucceeds(uploadBytes(ref(own(),path),payload,metadata));});
test('verified owner lists backups',async()=>{await assertSucceeds(listAll(ref(own(),`backups/${owner}`)));});
test('verified owner reads backup',async()=>{await assertSucceeds(getBytes(ref(own(),path)));});
test('unauthenticated cannot read or list',async()=>{const s=env.unauthenticatedContext().storage();await assertFails(getBytes(ref(s,path)));await assertFails(listAll(ref(s,`backups/${owner}`)));});
test('different account cannot read, list, overwrite or delete',async()=>{const s=env.authenticatedContext('someone-else',{email:'other@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}}).storage();await assertFails(getBytes(ref(s,path)));await assertFails(listAll(ref(s,`backups/${owner}`)));await assertFails(uploadBytes(ref(s,path),payload,metadata));await assertFails(deleteObject(ref(s,path)));});
test('UID without Google identity rejected',async()=>{await assertFails(getBytes(ref(env.authenticatedContext(owner).storage(),path)));});
test('phone-only identity rejected',async()=>{await assertFails(getBytes(ref(env.authenticatedContext(owner,{phone_number:'+16505550101',firebase:{sign_in_provider:'phone'}}).storage(),path)));});
test('verified email from another provider rejected',async()=>{await assertFails(getBytes(ref(env.authenticatedContext(owner,{email:'owner@example.test',email_verified:true,firebase:{sign_in_provider:'password'}}).storage(),path)));});
test('unverified Google email rejected',async()=>{await assertFails(getBytes(ref(env.authenticatedContext(owner,{email:'owner@example.test',email_verified:false,firebase:{sign_in_provider:'google.com'}}).storage(),path)));});
test('complete snapshot and metadata immutable',async()=>{const s=own();await assertFails(uploadBytes(ref(s,path),payload,metadata));await assertFails(updateMetadata(ref(s,path),{customMetadata:{label:'private'}}));});
test('invalid paths and MIME types rejected',async()=>{const s=own();await assertFails(uploadBytes(ref(s,`backups/${owner}/card.png`),payload,metadata));await assertFails(uploadBytes(ref(s,`backups/${owner}/22222222-2222-4222-8222-222222222222.omnibak`),payload,{contentType:'image/png'}));await assertFails(uploadBytes(ref(s,`public/${filename}`),payload,metadata));});
test('empty upload rejected',async()=>{await assertFails(uploadBytes(ref(own(),`backups/${owner}/33333333-3333-4333-8333-333333333333.omnibak`),new Uint8Array(),metadata));});
test('owner can delete obsolete backup',async()=>{await assertSucceeds(deleteObject(ref(own(),path)));});
const keyPath=`keys/${owner}/backup-key-v1`;
test('owner creates and reads 32-byte account key',async()=>{await assertSucceeds(uploadBytes(ref(own(),keyPath),new Uint8Array(32).fill(7),metadata));await assertSucceeds(getBytes(ref(own(),keyPath)));});
test('account recovery key cannot be replaced, changed, deleted or listed',async()=>{await assertFails(uploadBytes(ref(own(),keyPath),new Uint8Array(32).fill(8),metadata));await assertFails(updateMetadata(ref(own(),keyPath),{contentType:'text/plain'}));await assertFails(deleteObject(ref(own(),keyPath)));await assertFails(listAll(ref(own(),`keys/${owner}`)));});
test('account recovery key inaccessible to anonymous, other and phone accounts',async()=>{for(const s of [env.unauthenticatedContext().storage(),env.authenticatedContext('other',{email:'owner@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}}).storage(),env.authenticatedContext(owner,{phone_number:'+16505550101',firebase:{sign_in_provider:'phone'}}).storage()]){await assertFails(getBytes(ref(s,keyPath)));await assertFails(uploadBytes(ref(s,keyPath),new Uint8Array(32),metadata));}});
test('account key rejects wrong size, MIME and path',async()=>{const uid='new-key-owner';const s=env.authenticatedContext(uid,{email:'key@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}}).storage();for(const size of [0,31,33])await assertFails(uploadBytes(ref(s,`keys/${uid}/backup-key-v1`),new Uint8Array(size),metadata));await assertFails(uploadBytes(ref(s,`keys/${uid}/backup-key-v1`),new Uint8Array(32),{contentType:'text/plain'}));await assertFails(uploadBytes(ref(s,`keys/${uid}/other`),new Uint8Array(32),metadata));});
